# Form implementation generated from reading ui file '/Volumes/DATA/1. Erwin Save/pv-Week3/UI/export_page.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ExportPage(object):
    def setupUi(self, ExportPage):
        ExportPage.setObjectName("ExportPage")
        ExportPage.resize(800, 600)
        self.main_layout = QtWidgets.QVBoxLayout(ExportPage)
        self.main_layout.setContentsMargins(15, 15, 15, 15)
        self.main_layout.setSpacing(10)
        self.main_layout.setObjectName("main_layout")
        self.title_label = QtWidgets.QLabel(parent=ExportPage)
        self.title_label.setObjectName("title_label")
        self.main_layout.addWidget(self.title_label)
        self.export_frame = QtWidgets.QFrame(parent=ExportPage)
        self.export_frame.setMinimumSize(QtCore.QSize(0, 180))
        self.export_frame.setMaximumSize(QtCore.QSize(16777215, 200))
        self.export_frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.export_frame.setObjectName("export_frame")
        self.export_layout = QtWidgets.QVBoxLayout(self.export_frame)
        self.export_layout.setContentsMargins(20, 15, 20, 15)
        self.export_layout.setObjectName("export_layout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.export_layout.addItem(spacerItem)
        self.export_title_label = QtWidgets.QLabel(parent=self.export_frame)
        self.export_title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.export_title_label.setWordWrap(True)
        self.export_title_label.setObjectName("export_title_label")
        self.export_layout.addWidget(self.export_title_label)
        self.export_subtitle_label = QtWidgets.QLabel(parent=self.export_frame)
        self.export_subtitle_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.export_subtitle_label.setWordWrap(True)
        self.export_subtitle_label.setObjectName("export_subtitle_label")
        self.export_layout.addWidget(self.export_subtitle_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.export_layout.addItem(spacerItem1)
        self.export_button_layout = QtWidgets.QHBoxLayout()
        self.export_button_layout.setObjectName("export_button_layout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.export_button_layout.addItem(spacerItem2)
        self.export_button = QtWidgets.QPushButton(parent=self.export_frame)
        self.export_button.setMinimumSize(QtCore.QSize(150, 40))
        self.export_button.setMaximumSize(QtCore.QSize(150, 40))
        self.export_button.setObjectName("export_button")
        self.export_button_layout.addWidget(self.export_button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.export_button_layout.addItem(spacerItem3)
        self.export_layout.addLayout(self.export_button_layout)
        self.main_layout.addWidget(self.export_frame)
        self.preview_group = QtWidgets.QGroupBox(parent=ExportPage)
        self.preview_group.setObjectName("preview_group")
        self.preview_layout = QtWidgets.QVBoxLayout(self.preview_group)
        self.preview_layout.setSpacing(2)
        self.preview_layout.setObjectName("preview_layout")
        self.preview_heading = QtWidgets.QLabel(parent=self.preview_group)
        self.preview_heading.setObjectName("preview_heading")
        self.preview_layout.addWidget(self.preview_heading)
        self.info_label = QtWidgets.QLabel(parent=self.preview_group)
        self.info_label.setObjectName("info_label")
        self.preview_layout.addWidget(self.info_label)
        self.preview_table = QtWidgets.QTableWidget(parent=self.preview_group)
        self.preview_table.setMinimumSize(QtCore.QSize(0, 220))
        self.preview_table.setMaximumSize(QtCore.QSize(16777215, 220))
        self.preview_table.setAlternatingRowColors(True)
        self.preview_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.preview_table.setColumnCount(7)
        self.preview_table.setObjectName("preview_table")
        self.preview_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.preview_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.preview_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.preview_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.preview_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.preview_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.preview_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.preview_table.setHorizontalHeaderItem(6, item)
        self.preview_table.horizontalHeader().setVisible(True)
        self.preview_table.verticalHeader().setVisible(True)
        self.preview_layout.addWidget(self.preview_table)
        self.stats_label = QtWidgets.QLabel(parent=self.preview_group)
        self.stats_label.setObjectName("stats_label")
        self.preview_layout.addWidget(self.stats_label)
        self.main_layout.addWidget(self.preview_group)

        self.retranslateUi(ExportPage)
        QtCore.QMetaObject.connectSlotsByName(ExportPage)

    def retranslateUi(self, ExportPage):
        _translate = QtCore.QCoreApplication.translate
        ExportPage.setWindowTitle(_translate("ExportPage", "Halaman Ekspor"))
        self.title_label.setText(_translate("ExportPage", "Ekspor Data"))
        self.title_label.setStyleSheet(_translate("ExportPage", "QLabel {\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    color: #2c3e50;\n"
"    margin-bottom: 10px;\n"
"}"))
        self.export_frame.setStyleSheet(_translate("ExportPage", "QFrame#exportSection {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 #e3f2fd, stop:1 #bbdefb);\n"
"    border-radius: 16px;\n"
"    border: 2px solid #dee2e6;\n"
"}"))
        self.export_title_label.setText(_translate("ExportPage", "Apakah Anda ingin mengekspor ke CSV?"))
        self.export_title_label.setStyleSheet(_translate("ExportPage", "QLabel {\n"
"    font-size: 22px; \n"
"    font-weight: bold; \n"
"    color: #2c3e50;\n"
"    margin-bottom: 5px;\n"
"}"))
        self.export_subtitle_label.setText(_translate("ExportPage", "Klik tombol di bawah dan pilih tempat untuk menyimpan file CSV ini"))
        self.export_subtitle_label.setStyleSheet(_translate("ExportPage", "QLabel {\n"
"    font-size: 14px; \n"
"    color: #495057; \n"
"    margin-bottom: 10px;\n"
"}"))
        self.export_button.setText(_translate("ExportPage", "✓ Ayo Lakukan!"))
        self.export_button.setStyleSheet(_translate("ExportPage", "QPushButton {\n"
"    background-color: #28a745;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 10px 20px;\n"
"    border-radius: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #218838;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1e7e34;\n"
"}"))
        self.preview_group.setStyleSheet(_translate("ExportPage", "QGroupBox {\n"
"    border: 1px solid #dee2e6;\n"
"    border-radius: 8px;\n"
"    padding-top: 8px;\n"
"    margin-top: 3px;\n"
"    background-color: #ffffff;\n"
"}"))
        self.preview_heading.setText(_translate("ExportPage", "Pratinjau Data"))
        self.preview_heading.setStyleSheet(_translate("ExportPage", "QLabel {\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    color: #2c3e50;\n"
"    margin-bottom: 0px;\n"
"    padding: 2px 0;\n"
"}"))
        self.info_label.setText(_translate("ExportPage", "Pratinjau data yang akan diekspor:"))
        self.info_label.setStyleSheet(_translate("ExportPage", "QLabel {\n"
"    color: #6c757d; \n"
"    font-size: 12px; \n"
"    margin-bottom: 3px; \n"
"    margin-top: 0px;\n"
"    padding: 0px;\n"
"}"))
        self.preview_table.setSortingEnabled(False)
        self.preview_table.setStyleSheet(_translate("ExportPage", "QTableWidget {\n"
"    gridline-color: #dee2e6;\n"
"    background-color: #ffffff;\n"
"    alternate-background-color: #f8f9fa;\n"
"    border: 1px solid #dee2e6;\n"
"    font-size: 12pt;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 8px 6px;\n"
"    border-bottom: 1px solid #dee2e6;\n"
"    font-size: 12pt;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #007bff;\n"
"    color: white;\n"
"}\n"
"QTableWidget QHeaderView { \n"
"    background-color: #e9ecef;\n"
"    font-size: 12pt;\n"
"}\n"
"QTableWidget QHeaderView::section { \n"
"    background-color: #e9ecef;\n"
"    color: #495057;\n"
"    padding: 10px 8px; \n"
"    border: 1px solid #dee2e6; \n"
"    font-weight: bold;\n"
"    font-size: 12pt;\n"
"    min-height: 30px;\n"
"    text-align: center;\n"
"}\n"
"QTableWidget QHeaderView::section:hover {\n"
"    background-color: #dee2e6;\n"
"}\n"
"QTableWidget QHeaderView::section:pressed {\n"
"    background-color: #ced4da;\n"
"}\n"
"QTableWidget QHeaderView[orientation=\"1\"]::section {\n"
"    background-color: #e9ecef;\n"
"    color: #495057;\n"
"    border: 1px solid #dee2e6;\n"
"    font-size: 12pt;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    padding: 5px;\n"
"    min-width: 35px;\n"
"}\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #e9ecef;\n"
"    border: 1px solid #dee2e6;\n"
"}"))
        item = self.preview_table.horizontalHeaderItem(0)
        item.setText(_translate("ExportPage", "Tanggal"))
        item = self.preview_table.horizontalHeaderItem(1)
        item.setText(_translate("ExportPage", "Aktivitas"))
        item = self.preview_table.horizontalHeaderItem(2)
        item.setText(_translate("ExportPage", "Waktu Mulai"))
        item = self.preview_table.horizontalHeaderItem(3)
        item.setText(_translate("ExportPage", "Waktu Berakhir"))
        item = self.preview_table.horizontalHeaderItem(4)
        item.setText(_translate("ExportPage", "Durasi"))
        item = self.preview_table.horizontalHeaderItem(5)
        item.setText(_translate("ExportPage", "Status"))
        item = self.preview_table.horizontalHeaderItem(6)
        item.setText(_translate("ExportPage", "Dibuat"))
        self.stats_label.setText(_translate("ExportPage", "Total: 0 tugas | Selesai: 0 | Tertunda: 0"))
        self.stats_label.setStyleSheet(_translate("ExportPage", "QLabel {\n"
"    color: #495057; \n"
"    font-size: 11px; \n"
"    margin-top: 3px;\n"
"}"))
