# Form implementation generated from reading ui file '/Volumes/DATA/1. Erwin Save/pv-Week3/UI/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.header_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.header_widget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.header_widget.setMinimumSize(QtCore.QSize(0, 80))
        self.header_widget.setObjectName("header_widget")
        self.header_layout = QtWidgets.QHBoxLayout(self.header_widget)
        self.header_layout.setContentsMargins(20, 10, 20, 10)
        self.header_layout.setObjectName("header_layout")
        self.left_section = QtWidgets.QHBoxLayout()
        self.left_section.setObjectName("left_section")
        self.logo_icon = QtWidgets.QLabel(parent=self.header_widget)
        self.logo_icon.setMinimumSize(QtCore.QSize(50, 50))
        self.logo_icon.setMaximumSize(QtCore.QSize(50, 50))
        self.logo_icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logo_icon.setObjectName("logo_icon")
        self.left_section.addWidget(self.logo_icon)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.left_section.addItem(spacerItem)
        self.nav_layout = QtWidgets.QHBoxLayout()
        self.nav_layout.setSpacing(5)
        self.nav_layout.setObjectName("nav_layout")
        self.schedule_button = QtWidgets.QPushButton(parent=self.header_widget)
        self.schedule_button.setCheckable(True)
        self.schedule_button.setObjectName("schedule_button")
        self.nav_layout.addWidget(self.schedule_button)
        self.export_button = QtWidgets.QPushButton(parent=self.header_widget)
        self.export_button.setCheckable(True)
        self.export_button.setObjectName("export_button")
        self.nav_layout.addWidget(self.export_button)
        self.profile_button = QtWidgets.QPushButton(parent=self.header_widget)
        self.profile_button.setCheckable(True)
        self.profile_button.setObjectName("profile_button")
        self.nav_layout.addWidget(self.profile_button)
        self.left_section.addLayout(self.nav_layout)
        self.header_layout.addLayout(self.left_section)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.header_layout.addItem(spacerItem1)
        self.user_info_layout = QtWidgets.QHBoxLayout()
        self.user_info_layout.setObjectName("user_info_layout")
        self.header_profile_pic = QtWidgets.QLabel(parent=self.header_widget)
        self.header_profile_pic.setMinimumSize(QtCore.QSize(40, 40))
        self.header_profile_pic.setMaximumSize(QtCore.QSize(40, 40))
        self.header_profile_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.header_profile_pic.setObjectName("header_profile_pic")
        self.user_info_layout.addWidget(self.header_profile_pic)
        self.user_label = QtWidgets.QLabel(parent=self.header_widget)
        self.user_label.setObjectName("user_label")
        self.user_info_layout.addWidget(self.user_label)
        self.header_layout.addLayout(self.user_info_layout)
        self.main_layout.addWidget(self.header_widget)
        self.stacked_widget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stacked_widget.setObjectName("stacked_widget")
        self.schedule_page_placeholder = QtWidgets.QWidget()
        self.schedule_page_placeholder.setObjectName("schedule_page_placeholder")
        self.schedule_placeholder_layout = QtWidgets.QVBoxLayout(self.schedule_page_placeholder)
        self.schedule_placeholder_layout.setObjectName("schedule_placeholder_layout")
        self.schedule_placeholder_label = QtWidgets.QLabel(parent=self.schedule_page_placeholder)
        self.schedule_placeholder_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.schedule_placeholder_label.setObjectName("schedule_placeholder_label")
        self.schedule_placeholder_layout.addWidget(self.schedule_placeholder_label)
        self.stacked_widget.addWidget(self.schedule_page_placeholder)
        self.export_page_placeholder = QtWidgets.QWidget()
        self.export_page_placeholder.setObjectName("export_page_placeholder")
        self.export_placeholder_layout = QtWidgets.QVBoxLayout(self.export_page_placeholder)
        self.export_placeholder_layout.setObjectName("export_placeholder_layout")
        self.export_placeholder_label = QtWidgets.QLabel(parent=self.export_page_placeholder)
        self.export_placeholder_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.export_placeholder_label.setObjectName("export_placeholder_label")
        self.export_placeholder_layout.addWidget(self.export_placeholder_label)
        self.stacked_widget.addWidget(self.export_page_placeholder)
        self.profile_page_placeholder = QtWidgets.QWidget()
        self.profile_page_placeholder.setObjectName("profile_page_placeholder")
        self.profile_placeholder_layout = QtWidgets.QVBoxLayout(self.profile_page_placeholder)
        self.profile_placeholder_layout.setObjectName("profile_placeholder_layout")
        self.profile_placeholder_label = QtWidgets.QLabel(parent=self.profile_page_placeholder)
        self.profile_placeholder_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.profile_placeholder_label.setObjectName("profile_placeholder_label")
        self.profile_placeholder_layout.addWidget(self.profile_placeholder_label)
        self.stacked_widget.addWidget(self.profile_page_placeholder)
        self.main_layout.addWidget(self.stacked_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(parent=self.menubar)
        self.file_menu.setObjectName("file_menu")
        self.edit_menu = QtWidgets.QMenu(parent=self.menubar)
        self.edit_menu.setObjectName("edit_menu")
        self.view_menu = QtWidgets.QMenu(parent=self.menubar)
        self.view_menu.setObjectName("view_menu")
        self.help_menu = QtWidgets.QMenu(parent=self.menubar)
        self.help_menu.setObjectName("help_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.new_task_action = QtGui.QAction(parent=MainWindow)
        self.new_task_action.setObjectName("new_task_action")
        self.export_action = QtGui.QAction(parent=MainWindow)
        self.export_action.setObjectName("export_action")
        self.exit_action = QtGui.QAction(parent=MainWindow)
        self.exit_action.setObjectName("exit_action")
        self.paste_action = QtGui.QAction(parent=MainWindow)
        self.paste_action.setObjectName("paste_action")
        self.toggle_profile_dock_action = QtGui.QAction(parent=MainWindow)
        self.toggle_profile_dock_action.setObjectName("toggle_profile_dock_action")
        self.about_action = QtGui.QAction(parent=MainWindow)
        self.about_action.setObjectName("about_action")
        self.user_guide_action = QtGui.QAction(parent=MainWindow)
        self.user_guide_action.setObjectName("user_guide_action")
        self.file_menu.addAction(self.new_task_action)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.export_action)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.exit_action)
        self.edit_menu.addAction(self.paste_action)
        self.view_menu.addAction(self.toggle_profile_dock_action)
        self.help_menu.addAction(self.about_action)
        self.help_menu.addSeparator()
        self.help_menu.addAction(self.user_guide_action)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.edit_menu.menuAction())
        self.menubar.addAction(self.view_menu.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())

        self.retranslateUi(MainWindow)
        self.stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Trackerin - To-Do Activity Tracker"))
        MainWindow.setStyleSheet(_translate("MainWindow", "QMainWindow {\n"
"    background-color: #f8f9fa;\n"
"}"))
        self.header_widget.setStyleSheet(_translate("MainWindow", "QWidget#headerWidget {\n"
"    background-color: #ffffff;\n"
"    border-bottom: 1px solid #dee2e6;\n"
"}"))
        self.logo_icon.setText(_translate("MainWindow", "📋"))
        self.logo_icon.setStyleSheet(_translate("MainWindow", "font-size: 32px;"))
        self.schedule_button.setText(_translate("MainWindow", "📅 Jadwal"))
        self.schedule_button.setStyleSheet(_translate("MainWindow", "QPushButton#navButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #6c757d;\n"
"    font-size: 16px;\n"
"    font-weight: 500;\n"
"    padding: 12px 20px;\n"
"    margin: 5px;\n"
"    border-radius: 8px;\n"
"    min-width: 100px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QPushButton#navButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QPushButton#navButton:checked {\n"
"    background-color: #007bff;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton#navButton:pressed {\n"
"    background-color: #0056b3;\n"
"    color: #ffffff;\n"
"}"))
        self.export_button.setText(_translate("MainWindow", "📊 Ekspor"))
        self.profile_button.setText(_translate("MainWindow", "👤 Profil"))
        self.header_profile_pic.setText(_translate("MainWindow", "👤"))
        self.header_profile_pic.setStyleSheet(_translate("MainWindow", "QLabel {\n"
"    background-color: #007bff;\n"
"    color: #ffffff;\n"
"    border-radius: 20px;\n"
"    font-size: 20px;\n"
"}"))
        self.user_label.setText(_translate("MainWindow", "Muhamad Erwin Hariadinata\n"
"Student"))
        self.user_label.setStyleSheet(_translate("MainWindow", "QLabel {\n"
"    color: #2c3e50;\n"
"    font-size: 12px;\n"
"    margin-left: 10px;\n"
"}"))
        self.schedule_placeholder_label.setText(_translate("MainWindow", "Halaman Jadwal akan dimuat di sini"))
        self.export_placeholder_label.setText(_translate("MainWindow", "Halaman Ekspor akan dimuat di sini"))
        self.profile_placeholder_label.setText(_translate("MainWindow", "Halaman Profil akan dimuat di sini"))
        self.file_menu.setTitle(_translate("MainWindow", "Berkas"))
        self.edit_menu.setTitle(_translate("MainWindow", "Edit"))
        self.view_menu.setTitle(_translate("MainWindow", "Tampilan"))
        self.help_menu.setTitle(_translate("MainWindow", "Bantuan"))
        self.statusbar.setStyleSheet(_translate("MainWindow", "QStatusBar {\n"
"    background-color: #007bff;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 5px 15px;\n"
"    font-size: 12px;\n"
"    max-height: 25px;\n"
"    min-height: 25px;\n"
"}\n"
"QStatusBar::item {\n"
"    border: none;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"QStatusBar QLabel {\n"
"    color: #ffffff;\n"
"    font-size: 12px;\n"
"    margin: 0px;\n"
"    padding: 2px 5px;\n"
"}"))
        self.new_task_action.setText(_translate("MainWindow", "Tugas Baru"))
        self.new_task_action.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.export_action.setText(_translate("MainWindow", "Ekspor ke CSV"))
        self.export_action.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.exit_action.setText(_translate("MainWindow", "Keluar"))
        self.exit_action.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.paste_action.setText(_translate("MainWindow", "Tempel dari Clipboard"))
        self.paste_action.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.toggle_profile_dock_action.setText(_translate("MainWindow", "Toggle Dok Profil"))
        self.about_action.setText(_translate("MainWindow", "Informasi Aplikasi"))
        self.about_action.setShortcut(_translate("MainWindow", "F1"))
        self.user_guide_action.setText(_translate("MainWindow", "Panduan Pengguna"))
