# Form implementation generated from reading ui file '/Volumes/DATA/1. Erwin Save/pv-Week3/UI/profile_dock.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProfileDock(object):
    def setupUi(self, ProfileDock):
        ProfileDock.setObjectName("ProfileDock")
        ProfileDock.resize(320, 600)
        ProfileDock.setMinimumSize(QtCore.QSize(280, 0))
        ProfileDock.setMaximumSize(QtCore.QSize(350, 16777215))
        self.dock_layout = QtWidgets.QVBoxLayout(ProfileDock)
        self.dock_layout.setContentsMargins(15, 15, 15, 15)
        self.dock_layout.setSpacing(15)
        self.dock_layout.setObjectName("dock_layout")
        self.profile_view_label = QtWidgets.QLabel(parent=ProfileDock)
        self.profile_view_label.setObjectName("profile_view_label")
        self.dock_layout.addWidget(self.profile_view_label)
        self.pic_layout = QtWidgets.QHBoxLayout()
        self.pic_layout.setObjectName("pic_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.pic_layout.addItem(spacerItem)
        self.profile_pic_frame = QtWidgets.QLabel(parent=ProfileDock)
        self.profile_pic_frame.setMinimumSize(QtCore.QSize(100, 100))
        self.profile_pic_frame.setMaximumSize(QtCore.QSize(100, 100))
        self.profile_pic_frame.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.profile_pic_frame.setObjectName("profile_pic_frame")
        self.pic_layout.addWidget(self.profile_pic_frame)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.pic_layout.addItem(spacerItem1)
        self.dock_layout.addLayout(self.pic_layout)
        self.name_label = QtWidgets.QLabel(parent=ProfileDock)
        self.name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.dock_layout.addWidget(self.name_label)
        self.change_profile_btn = QtWidgets.QPushButton(parent=ProfileDock)
        self.change_profile_btn.setObjectName("change_profile_btn")
        self.dock_layout.addWidget(self.change_profile_btn)
        self.separator = QtWidgets.QLabel(parent=ProfileDock)
        self.separator.setMinimumSize(QtCore.QSize(0, 1))
        self.separator.setMaximumSize(QtCore.QSize(16777215, 1))
        self.separator.setObjectName("separator")
        self.dock_layout.addWidget(self.separator)
        self.profile_form_label = QtWidgets.QLabel(parent=ProfileDock)
        self.profile_form_label.setObjectName("profile_form_label")
        self.dock_layout.addWidget(self.profile_form_label)
        self.name_layout = QtWidgets.QVBoxLayout()
        self.name_layout.setObjectName("name_layout")
        self.name_input_label = QtWidgets.QLabel(parent=ProfileDock)
        self.name_input_label.setObjectName("name_input_label")
        self.name_layout.addWidget(self.name_input_label)
        self.name_input = QtWidgets.QLineEdit(parent=ProfileDock)
        self.name_input.setObjectName("name_input")
        self.name_layout.addWidget(self.name_input)
        self.dock_layout.addLayout(self.name_layout)
        self.email_layout = QtWidgets.QVBoxLayout()
        self.email_layout.setObjectName("email_layout")
        self.email_input_label = QtWidgets.QLabel(parent=ProfileDock)
        self.email_input_label.setObjectName("email_input_label")
        self.email_layout.addWidget(self.email_input_label)
        self.email_input = QtWidgets.QLineEdit(parent=ProfileDock)
        self.email_input.setObjectName("email_input")
        self.email_layout.addWidget(self.email_input)
        self.dock_layout.addLayout(self.email_layout)
        self.id_layout = QtWidgets.QVBoxLayout()
        self.id_layout.setObjectName("id_layout")
        self.id_input_label = QtWidgets.QLabel(parent=ProfileDock)
        self.id_input_label.setObjectName("id_input_label")
        self.id_layout.addWidget(self.id_input_label)
        self.id_input = QtWidgets.QLineEdit(parent=ProfileDock)
        self.id_input.setObjectName("id_input")
        self.id_layout.addWidget(self.id_input)
        self.dock_layout.addLayout(self.id_layout)
        self.status_layout = QtWidgets.QVBoxLayout()
        self.status_layout.setObjectName("status_layout")
        self.status_input_label = QtWidgets.QLabel(parent=ProfileDock)
        self.status_input_label.setObjectName("status_input_label")
        self.status_layout.addWidget(self.status_input_label)
        self.status_combo = QtWidgets.QComboBox(parent=ProfileDock)
        self.status_combo.setObjectName("status_combo")
        self.status_combo.addItem("")
        self.status_combo.addItem("")
        self.status_combo.addItem("")
        self.status_combo.addItem("")
        self.status_layout.addWidget(self.status_combo)
        self.dock_layout.addLayout(self.status_layout)
        self.submit_button = QtWidgets.QPushButton(parent=ProfileDock)
        self.submit_button.setObjectName("submit_button")
        self.dock_layout.addWidget(self.submit_button)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.dock_layout.addItem(spacerItem2)

        self.retranslateUi(ProfileDock)
        QtCore.QMetaObject.connectSlotsByName(ProfileDock)

    def retranslateUi(self, ProfileDock):
        _translate = QtCore.QCoreApplication.translate
        ProfileDock.setWindowTitle(_translate("ProfileDock", "Dok Profil"))
        ProfileDock.setStyleSheet(_translate("ProfileDock", "QWidget {\n"
"    background-color: #ffffff;\n"
"    color: #2c3e50;\n"
"}"))
        self.profile_view_label.setText(_translate("ProfileDock", "Tampilan Profil"))
        self.profile_view_label.setStyleSheet(_translate("ProfileDock", "QLabel {\n"
"    font-weight: bold; \n"
"    font-size: 14px; \n"
"    color: #2c3e50; \n"
"    margin-bottom: 8px; \n"
"    padding: 2px 0;\n"
"}"))
        self.profile_pic_frame.setText(_translate("ProfileDock", "👤"))
        self.profile_pic_frame.setStyleSheet(_translate("ProfileDock", "QLabel {\n"
"    background-color: #495057;\n"
"    border-radius: 50px;\n"
"    border: 2px solid #dee2e6;\n"
"    color: white;\n"
"    font-size: 48px;\n"
"}"))
        self.name_label.setText(_translate("ProfileDock", "Muhamad Erwin Hariadinata"))
        self.name_label.setStyleSheet(_translate("ProfileDock", "QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #2c3e50;\n"
"    margin: 10px 0;\n"
"}"))
        self.change_profile_btn.setText(_translate("ProfileDock", "Ubah Profil"))
        self.change_profile_btn.setStyleSheet(_translate("ProfileDock", "QPushButton {\n"
"    background-color: #f8f9fa;\n"
"    border: 1px solid #dee2e6;\n"
"    border-radius: 6px;\n"
"    padding: 8px 16px;\n"
"    color: #2c3e50;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9ecef;\n"
"}"))
        self.separator.setStyleSheet(_translate("ProfileDock", "QLabel {\n"
"    background-color: #dee2e6; \n"
"    margin: 10px 0;\n"
"}"))
        self.profile_form_label.setText(_translate("ProfileDock", "Atur Profil Saya"))
        self.profile_form_label.setStyleSheet(_translate("ProfileDock", "QLabel {\n"
"    font-weight: bold; \n"
"    font-size: 14px; \n"
"    color: #2c3e50; \n"
"    margin-bottom: 8px; \n"
"    padding: 2px 0;\n"
"}"))
        self.name_input_label.setText(_translate("ProfileDock", "Nama Lengkap"))
        self.name_input_label.setStyleSheet(_translate("ProfileDock", "QLabel {\n"
"    color: #2c3e50; \n"
"    font-size: 12px; \n"
"    font-weight: 500;\n"
"}"))
        self.name_input.setPlaceholderText(_translate("ProfileDock", "Masukkan nama lengkap Anda (Ctrl+V untuk tempel)"))
        self.name_input.setStyleSheet(_translate("ProfileDock", "QLineEdit {\n"
"    border: 2px solid #dee2e6;\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    background-color: #ffffff;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #007bff;\n"
"}"))
        self.email_input_label.setText(_translate("ProfileDock", "Email"))
        self.email_input_label.setStyleSheet(_translate("ProfileDock", "QLabel {\n"
"    color: #2c3e50; \n"
"    font-size: 12px; \n"
"    font-weight: 500;\n"
"}"))
        self.email_input.setPlaceholderText(_translate("ProfileDock", "Masukkan email Anda (Ctrl+V untuk tempel)"))
        self.email_input.setStyleSheet(_translate("ProfileDock", "QLineEdit {\n"
"    border: 2px solid #dee2e6;\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    background-color: #ffffff;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #007bff;\n"
"}"))
        self.id_input_label.setText(_translate("ProfileDock", "ID Mahasiswa"))
        self.id_input_label.setStyleSheet(_translate("ProfileDock", "QLabel {\n"
"    color: #2c3e50; \n"
"    font-size: 12px; \n"
"    font-weight: 500;\n"
"}"))
        self.id_input.setPlaceholderText(_translate("ProfileDock", "Masukkan ID mahasiswa Anda (Ctrl+V untuk tempel)"))
        self.id_input.setStyleSheet(_translate("ProfileDock", "QLineEdit {\n"
"    border: 2px solid #dee2e6;\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    background-color: #ffffff;\n"
"    font-size: 14px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #007bff;\n"
"}"))
        self.status_input_label.setText(_translate("ProfileDock", "Jenis Status"))
        self.status_input_label.setStyleSheet(_translate("ProfileDock", "QLabel {\n"
"    color: #2c3e50; \n"
"    font-size: 12px; \n"
"    font-weight: 500;\n"
"}"))
        self.status_combo.setStyleSheet(_translate("ProfileDock", "QComboBox {\n"
"    border: 2px solid #dee2e6;\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    background-color: #ffffff;\n"
"    font-size: 14px;\n"
"    min-height: 20px;\n"
"    padding-right: 25px;\n"
"}\n"
"QComboBox:focus {\n"
"    border-color: #007bff;\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 20px;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 4px solid transparent;\n"
"    border-right: 4px solid transparent;\n"
"    border-top: 4px solid #6c757d;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"QComboBox::down-arrow:hover {\n"
"    border-top-color: #495057;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #dee2e6;\n"
"    background-color: #ffffff;\n"
"    selection-background-color: #007bff;\n"
"    selection-color: #ffffff;\n"
"}"))
        self.status_combo.setItemText(0, _translate("ProfileDock", "Mahasiswa"))
        self.status_combo.setItemText(1, _translate("ProfileDock", "Guru"))
        self.status_combo.setItemText(2, _translate("ProfileDock", "Staf"))
        self.status_combo.setItemText(3, _translate("ProfileDock", "Lainnya"))
        self.submit_button.setText(_translate("ProfileDock", "Kirim"))
        self.submit_button.setStyleSheet(_translate("ProfileDock", "QPushButton {\n"
"    background-color: #007bff;\n"
"    color: #ffffff;\n"
"    border: 2px solid #007bff;\n"
"    padding: 12px 24px;\n"
"    border-radius: 8px;\n"
"    font-size: 16px;\n"
"    font-weight: 500;\n"
"    min-width: 120px;\n"
"    min-height: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;\n"
"    border-color: #0056b3;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #004085;\n"
"    border-color: #004085;\n"
"}"))
