# Form implementation generated from reading ui file '/Volumes/DATA/1. Erwin Save/pv-Week3/UI/profile_page.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProfilePage(object):
    def setupUi(self, ProfilePage):
        ProfilePage.setObjectName("ProfilePage")
        ProfilePage.resize(800, 600)
        self.main_layout = QtWidgets.QVBoxLayout(ProfilePage)
        self.main_layout.setContentsMargins(15, 15, 15, 15)
        self.main_layout.setSpacing(10)
        self.main_layout.setObjectName("main_layout")
        self.title_label = QtWidgets.QLabel(parent=ProfilePage)
        self.title_label.setObjectName("title_label")
        self.main_layout.addWidget(self.title_label)
        self.search_layout = QtWidgets.QHBoxLayout()
        self.search_layout.setObjectName("search_layout")
        self.filter_button = QtWidgets.QPushButton(parent=ProfilePage)
        self.filter_button.setObjectName("filter_button")
        self.search_layout.addWidget(self.filter_button)
        self.search_input = QtWidgets.QLineEdit(parent=ProfilePage)
        self.search_input.setObjectName("search_input")
        self.search_layout.addWidget(self.search_input)
        self.main_layout.addLayout(self.search_layout)
        self.activity_table = QtWidgets.QTableWidget(parent=ProfilePage)
        self.activity_table.setAlternatingRowColors(True)
        self.activity_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.activity_table.setColumnCount(7)
        self.activity_table.setObjectName("activity_table")
        self.activity_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.activity_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.activity_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.activity_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.activity_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.activity_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.activity_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.activity_table.setHorizontalHeaderItem(6, item)
        self.activity_table.horizontalHeader().setVisible(True)
        self.activity_table.verticalHeader().setVisible(False)
        self.main_layout.addWidget(self.activity_table)
        self.pagination_label = QtWidgets.QLabel(parent=ProfilePage)
        self.pagination_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pagination_label.setObjectName("pagination_label")
        self.main_layout.addWidget(self.pagination_label)

        self.retranslateUi(ProfilePage)
        QtCore.QMetaObject.connectSlotsByName(ProfilePage)

    def retranslateUi(self, ProfilePage):
        _translate = QtCore.QCoreApplication.translate
        ProfilePage.setWindowTitle(_translate("ProfilePage", "Halaman Profil"))
        self.title_label.setText(_translate("ProfilePage", "Riwayat Aktivitas"))
        self.title_label.setStyleSheet(_translate("ProfilePage", "QLabel {\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    color: #2c3e50;\n"
"    margin-bottom: 20px;\n"
"}"))
        self.filter_button.setText(_translate("ProfilePage", "🔽 Filter"))
        self.filter_button.setStyleSheet(_translate("ProfilePage", "QPushButton {\n"
"    background-color: #f8f9fa;\n"
"    border: 1px solid #dee2e6;\n"
"    border-radius: 6px;\n"
"    padding: 8px 16px;\n"
"    color: #2c3e50;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9ecef;\n"
"}"))
        self.search_input.setPlaceholderText(_translate("ProfilePage", "Cari Pengguna berdasarkan Nama, Email atau Tanggal (Ctrl+V untuk tempel)"))
        self.search_input.setStyleSheet(_translate("ProfilePage", "QLineEdit#searchBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #dee2e6;\n"
"    border-radius: 20px;\n"
"    padding: 10px 15px;\n"
"    font-size: 14px;\n"
"    color: #2c3e50;\n"
"    min-width: 300px;\n"
"}\n"
"QLineEdit#searchBox:focus {\n"
"    border-color: #007bff;\n"
"}\n"
"QLineEdit#searchBox::placeholder {\n"
"    color: #6c757d;\n"
"    font-style: italic;\n"
"}"))
        self.activity_table.setSortingEnabled(True)
        self.activity_table.setStyleSheet(_translate("ProfilePage", "QTableWidget {\n"
"    gridline-color: #dee2e6;\n"
"    background-color: #ffffff;\n"
"    alternate-background-color: #f8f9fa;\n"
"    border: none;\n"
"    font-size: 12pt;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 10px 8px;\n"
"    border-bottom: 1px solid #dee2e6;\n"
"    font-size: 12pt;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #007bff;\n"
"    color: white;\n"
"}\n"
"QTableWidget QHeaderView { \n"
"    background-color: #e9ecef;\n"
"    font-size: 12pt;\n"
"}\n"
"QTableWidget QHeaderView::section { \n"
"    background-color: #e9ecef;\n"
"    color: #495057;\n"
"    padding: 12px 15px; \n"
"    border: 1px solid #dee2e6; \n"
"    font-weight: bold;\n"
"    font-size: 12pt;\n"
"    min-height: 40px;\n"
"    text-align: center;\n"
"}\n"
"QTableWidget QHeaderView::section:hover {\n"
"    background-color: #dee2e6;\n"
"}\n"
"QTableWidget QHeaderView::section:pressed {\n"
"    background-color: #ced4da;\n"
"}\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #e9ecef;\n"
"    border: 1px solid #dee2e6;\n"
"}"))
        item = self.activity_table.horizontalHeaderItem(0)
        item.setText(_translate("ProfilePage", "Tanggal"))
        item = self.activity_table.horizontalHeaderItem(1)
        item.setText(_translate("ProfilePage", "Aktivitas"))
        item = self.activity_table.horizontalHeaderItem(2)
        item.setText(_translate("ProfilePage", "Waktu Mulai"))
        item = self.activity_table.horizontalHeaderItem(3)
        item.setText(_translate("ProfilePage", "Waktu Berakhir"))
        item = self.activity_table.horizontalHeaderItem(4)
        item.setText(_translate("ProfilePage", "Durasi"))
        item = self.activity_table.horizontalHeaderItem(5)
        item.setText(_translate("ProfilePage", "Status"))
        item = self.activity_table.horizontalHeaderItem(6)
        item.setText(_translate("ProfilePage", "Aksi"))
        self.pagination_label.setText(_translate("ProfilePage", "1-10 dari 276"))
        self.pagination_label.setStyleSheet(_translate("ProfilePage", "QLabel {\n"
"    color: #6c757d; \n"
"    font-size: 12px;\n"
"}"))
