# Form implementation generated from reading ui file '/Volumes/DATA/1. Erwin Save/pv-Week3/UI/schedule_page.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SchedulePage(object):
    def setupUi(self, SchedulePage):
        SchedulePage.setObjectName("SchedulePage")
        SchedulePage.resize(1040, 600)
        self.main_layout = QtWidgets.QHBoxLayout(SchedulePage)
        self.main_layout.setContentsMargins(15, 15, 15, 15)
        self.main_layout.setSpacing(20)
        self.main_layout.setObjectName("main_layout")
        self.left_widget = QtWidgets.QWidget(parent=SchedulePage)
        self.left_widget.setMinimumSize(QtCore.QSize(620, 0))
        self.left_widget.setMaximumSize(QtCore.QSize(620, 16777215))
        self.left_widget.setObjectName("left_widget")
        self.left_layout = QtWidgets.QVBoxLayout(self.left_widget)
        self.left_layout.setContentsMargins(10, 0, 10, 0)
        self.left_layout.setSpacing(10)
        self.left_layout.setObjectName("left_layout")
        self.title_label = QtWidgets.QLabel(parent=self.left_widget)
        self.title_label.setObjectName("title_label")
        self.left_layout.addWidget(self.title_label)
        self.day_scroll_area = QtWidgets.QScrollArea(parent=self.left_widget)
        self.day_scroll_area.setMinimumSize(QtCore.QSize(0, 70))
        self.day_scroll_area.setMaximumSize(QtCore.QSize(16777215, 70))
        self.day_scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.day_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.day_scroll_area.setWidgetResizable(True)
        self.day_scroll_area.setObjectName("day_scroll_area")
        self.day_container = QtWidgets.QWidget()
        self.day_container.setGeometry(QtCore.QRect(0, 0, 598, 68))
        self.day_container.setObjectName("day_container")
        self.day_layout = QtWidgets.QHBoxLayout(self.day_container)
        self.day_layout.setContentsMargins(0, 0, 0, 0)
        self.day_layout.setSpacing(5)
        self.day_layout.setObjectName("day_layout")
        self.day_scroll_area.setWidget(self.day_container)
        self.left_layout.addWidget(self.day_scroll_area)
        self.current_day_label = QtWidgets.QLabel(parent=self.left_widget)
        self.current_day_label.setObjectName("current_day_label")
        self.left_layout.addWidget(self.current_day_label)
        self.task_scroll_area = QtWidgets.QScrollArea(parent=self.left_widget)
        self.task_scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.task_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.task_scroll_area.setWidgetResizable(True)
        self.task_scroll_area.setObjectName("task_scroll_area")
        self.task_container = QtWidgets.QWidget()
        self.task_container.setGeometry(QtCore.QRect(0, 0, 598, 69))
        self.task_container.setObjectName("task_container")
        self.task_layout = QtWidgets.QVBoxLayout(self.task_container)
        self.task_layout.setSpacing(8)
        self.task_layout.setObjectName("task_layout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.task_layout.addItem(spacerItem)
        self.task_scroll_area.setWidget(self.task_container)
        self.left_layout.addWidget(self.task_scroll_area)
        self.main_layout.addWidget(self.left_widget)
        self.right_widget = QtWidgets.QWidget(parent=SchedulePage)
        self.right_widget.setMinimumSize(QtCore.QSize(420, 0))
        self.right_widget.setMaximumSize(QtCore.QSize(420, 16777215))
        self.right_widget.setObjectName("right_widget")
        self.right_layout = QtWidgets.QVBoxLayout(self.right_widget)
        self.right_layout.setContentsMargins(0, 0, 0, 0)
        self.right_layout.setSpacing(15)
        self.right_layout.setObjectName("right_layout")
        self.calendar = QtWidgets.QCalendarWidget(parent=self.right_widget)
        self.calendar.setMinimumSize(QtCore.QSize(420, 280))
        self.calendar.setMaximumSize(QtCore.QSize(420, 280))
        self.calendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader)
        self.calendar.setObjectName("calendar")
        self.right_layout.addWidget(self.calendar)
        self.form_scroll_area = QtWidgets.QScrollArea(parent=self.right_widget)
        self.form_scroll_area.setMinimumSize(QtCore.QSize(420, 360))
        self.form_scroll_area.setMaximumSize(QtCore.QSize(420, 360))
        self.form_scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.form_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.form_scroll_area.setWidgetResizable(True)
        self.form_scroll_area.setObjectName("form_scroll_area")
        self.form_container = QtWidgets.QWidget()
        self.form_container.setGeometry(QtCore.QRect(0, 0, 418, 358))
        self.form_container.setObjectName("form_container")
        self.form_container_layout = QtWidgets.QVBoxLayout(self.form_container)
        self.form_container_layout.setContentsMargins(10, 10, 10, 30)
        self.form_container_layout.setObjectName("form_container_layout")
        self.form_widget = QtWidgets.QWidget(parent=self.form_container)
        self.form_widget.setObjectName("form_widget")
        self.form_layout = QtWidgets.QVBoxLayout(self.form_widget)
        self.form_layout.setContentsMargins(20, 15, 20, 15)
        self.form_layout.setSpacing(10)
        self.form_layout.setObjectName("form_layout")
        self.form_title_label = QtWidgets.QLabel(parent=self.form_widget)
        self.form_title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.form_title_label.setObjectName("form_title_label")
        self.form_layout.addWidget(self.form_title_label)
        self.start_date_label = QtWidgets.QLabel(parent=self.form_widget)
        self.start_date_label.setObjectName("start_date_label")
        self.form_layout.addWidget(self.start_date_label)
        self.start_date_edit = QtWidgets.QDateEdit(parent=self.form_widget)
        self.start_date_edit.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.start_date_edit.setObjectName("start_date_edit")
        self.form_layout.addWidget(self.start_date_edit)
        self.end_date_label = QtWidgets.QLabel(parent=self.form_widget)
        self.end_date_label.setObjectName("end_date_label")
        self.form_layout.addWidget(self.end_date_label)
        self.end_date_edit = QtWidgets.QDateEdit(parent=self.form_widget)
        self.end_date_edit.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.end_date_edit.setObjectName("end_date_edit")
        self.form_layout.addWidget(self.end_date_edit)
        self.start_time_label = QtWidgets.QLabel(parent=self.form_widget)
        self.start_time_label.setObjectName("start_time_label")
        self.form_layout.addWidget(self.start_time_label)
        self.start_time_edit = QtWidgets.QTimeEdit(parent=self.form_widget)
        self.start_time_edit.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.start_time_edit.setObjectName("start_time_edit")
        self.form_layout.addWidget(self.start_time_edit)
        self.end_time_label = QtWidgets.QLabel(parent=self.form_widget)
        self.end_time_label.setObjectName("end_time_label")
        self.form_layout.addWidget(self.end_time_label)
        self.end_time_edit = QtWidgets.QTimeEdit(parent=self.form_widget)
        self.end_time_edit.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.end_time_edit.setObjectName("end_time_edit")
        self.form_layout.addWidget(self.end_time_edit)
        self.activity_label = QtWidgets.QLabel(parent=self.form_widget)
        self.activity_label.setObjectName("activity_label")
        self.form_layout.addWidget(self.activity_label)
        self.activity_input = QtWidgets.QLineEdit(parent=self.form_widget)
        self.activity_input.setObjectName("activity_input")
        self.form_layout.addWidget(self.activity_input)
        self.submit_button = QtWidgets.QPushButton(parent=self.form_widget)
        self.submit_button.setObjectName("submit_button")
        self.form_layout.addWidget(self.submit_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.form_layout.addItem(spacerItem1)
        self.form_container_layout.addWidget(self.form_widget)
        self.form_scroll_area.setWidget(self.form_container)
        self.right_layout.addWidget(self.form_scroll_area)
        self.main_layout.addWidget(self.right_widget)

        self.retranslateUi(SchedulePage)
        QtCore.QMetaObject.connectSlotsByName(SchedulePage)

    def retranslateUi(self, SchedulePage):
        _translate = QtCore.QCoreApplication.translate
        SchedulePage.setWindowTitle(_translate("SchedulePage", "Halaman Jadwal"))
        self.title_label.setText(_translate("SchedulePage", "Pelacak Aktivitas Daftar Tugas"))
        self.title_label.setStyleSheet(_translate("SchedulePage", "QLabel {\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    color: #2c3e50;\n"
"    margin-bottom: 20px;\n"
"}"))
        self.current_day_label.setText(_translate("SchedulePage", "Hari Ini, Des 21"))
        self.current_day_label.setStyleSheet(_translate("SchedulePage", "QLabel {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #2c3e50;\n"
"    margin: 10px 0;\n"
"}"))
        self.calendar.setStyleSheet(_translate("SchedulePage", "QCalendarWidget {\n"
"    background-color: #007bff;\n"
"    color: #ffffff;\n"
"    border-radius: 12px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton {\n"
"    color: #ffffff;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton:hover {\n"
"    background-color: #0056b3;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QCalendarWidget QMenu {\n"
"    background-color: #007bff;\n"
"    color: #ffffff;\n"
"    border: 1px solid #0056b3;\n"
"}\n"
"\n"
"QCalendarWidget QSpinBox {\n"
"    background-color: #007bff;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCalendarWidget QAbstractItemView {\n"
"    background-color: #007bff;\n"
"    color: #ffffff;\n"
"    selection-background-color: #0056b3;\n"
"    outline: none;\n"
"}"))
        self.form_scroll_area.setStyleSheet(_translate("SchedulePage", "QScrollArea {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}"))
        self.form_widget.setStyleSheet(_translate("SchedulePage", "QWidget {\n"
"    background-color: #f8f9fa;\n"
"    border: 1px solid #dee2e6;\n"
"    border-radius: 8px;\n"
"    margin: 5px;\n"
"}"))
        self.form_title_label.setText(_translate("SchedulePage", "Form To-Do"))
        self.form_title_label.setStyleSheet(_translate("SchedulePage", "QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    color: #343a40;\n"
"    text-align: center;\n"
"    margin-bottom: 8px;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}"))
        self.start_date_label.setText(_translate("SchedulePage", "Tanggal Mulai"))
        self.start_date_label.setStyleSheet(_translate("SchedulePage", "QLabel {\n"
"    color: #495057; \n"
"    font-size: 13px; \n"
"    font-weight: 500; \n"
"    margin-bottom: 2px;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}"))
        self.start_date_edit.setStyleSheet(_translate("SchedulePage", "QDateEdit {\n"
"    padding: 8px 25px 8px 12px;\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 6px;\n"
"    font-size: 13px;\n"
"    background-color: #ffffff;\n"
"    color: #495057;\n"
"    min-height: 16px;\n"
"}\n"
"QDateEdit:focus { \n"
"    border-color: #80bdff; \n"
"    background-color: #ffffff;\n"
"}"))
        self.end_date_label.setText(_translate("SchedulePage", "Tanggal Berakhir"))
        self.end_date_label.setStyleSheet(_translate("SchedulePage", "QLabel {\n"
"    color: #495057; \n"
"    font-size: 13px; \n"
"    font-weight: 500; \n"
"    margin-bottom: 2px;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}"))
        self.end_date_edit.setStyleSheet(_translate("SchedulePage", "QDateEdit {\n"
"    padding: 8px 25px 8px 12px;\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 6px;\n"
"    font-size: 13px;\n"
"    background-color: #ffffff;\n"
"    color: #495057;\n"
"    min-height: 16px;\n"
"}\n"
"QDateEdit:focus { \n"
"    border-color: #80bdff; \n"
"    background-color: #ffffff;\n"
"}"))
        self.start_time_label.setText(_translate("SchedulePage", "Waktu Mulai"))
        self.start_time_label.setStyleSheet(_translate("SchedulePage", "QLabel {\n"
"    color: #495057; \n"
"    font-size: 13px; \n"
"    font-weight: 500; \n"
"    margin-bottom: 2px;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}"))
        self.start_time_edit.setDisplayFormat(_translate("SchedulePage", "hh:mm AP"))
        self.start_time_edit.setStyleSheet(_translate("SchedulePage", "QTimeEdit {\n"
"    padding: 8px 25px 8px 12px;\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 6px;\n"
"    font-size: 13px;\n"
"    background-color: #ffffff;\n"
"    color: #495057;\n"
"    min-height: 16px;\n"
"}\n"
"QTimeEdit:focus { \n"
"    border-color: #80bdff; \n"
"    background-color: #ffffff;\n"
"}"))
        self.end_time_label.setText(_translate("SchedulePage", "Waktu Berakhir"))
        self.end_time_label.setStyleSheet(_translate("SchedulePage", "QLabel {\n"
"    color: #495057; \n"
"    font-size: 13px; \n"
"    font-weight: 500; \n"
"    margin-bottom: 2px;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}"))
        self.end_time_edit.setDisplayFormat(_translate("SchedulePage", "hh:mm AP"))
        self.end_time_edit.setStyleSheet(_translate("SchedulePage", "QTimeEdit {\n"
"    padding: 8px 25px 8px 12px;\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 6px;\n"
"    font-size: 13px;\n"
"    background-color: #ffffff;\n"
"    color: #495057;\n"
"    min-height: 16px;\n"
"}\n"
"QTimeEdit:focus { \n"
"    border-color: #80bdff; \n"
"    background-color: #ffffff;\n"
"}"))
        self.activity_label.setText(_translate("SchedulePage", "Input Aktivitas"))
        self.activity_label.setStyleSheet(_translate("SchedulePage", "QLabel {\n"
"    color: #495057; \n"
"    font-size: 13px; \n"
"    font-weight: 500; \n"
"    margin-bottom: 2px;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}"))
        self.activity_input.setPlaceholderText(_translate("SchedulePage", "Masukkan Aktivitas To-Do"))
        self.activity_input.setStyleSheet(_translate("SchedulePage", "QLineEdit {\n"
"    padding: 8px 12px;\n"
"    border: 1px solid #ced4da;\n"
"    border-radius: 6px;\n"
"    font-size: 13px;\n"
"    background-color: #ffffff;\n"
"    color: #495057;\n"
"    min-height: 16px;\n"
"}\n"
"QLineEdit:focus { \n"
"    border-color: #80bdff; \n"
"    background-color: #ffffff;\n"
"}\n"
"QLineEdit::placeholder { \n"
"    color: #adb5bd; \n"
"}"))
        self.submit_button.setText(_translate("SchedulePage", "Kirim"))
        self.submit_button.setStyleSheet(_translate("SchedulePage", "QPushButton {\n"
"    background-color: #1e3a8a;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 10px 20px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    margin-top: 8px;\n"
"    min-height: 16px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1e40af;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1d4ed8;\n"
"}"))
