# Form implementation generated from reading ui file '/Volumes/DATA/1. Erwin Save/pv-Week3/UI/task_card.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TaskCard(object):
    def setupUi(self, TaskCard):
        TaskCard.setObjectName("TaskCard")
        TaskCard.resize(550, 200)
        TaskCard.setMinimumSize(QtCore.QSize(550, 0))
        TaskCard.setMaximumSize(QtCore.QSize(550, 16777215))
        TaskCard.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.main_layout = QtWidgets.QVBoxLayout(TaskCard)
        self.main_layout.setContentsMargins(15, 15, 15, 15)
        self.main_layout.setSpacing(8)
        self.main_layout.setObjectName("main_layout")
        self.header_layout = QtWidgets.QHBoxLayout()
        self.header_layout.setObjectName("header_layout")
        self.title_label = QtWidgets.QLabel(parent=TaskCard)
        self.title_label.setObjectName("title_label")
        self.header_layout.addWidget(self.title_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.header_layout.addItem(spacerItem)
        self.status_label = QtWidgets.QLabel(parent=TaskCard)
        self.status_label.setObjectName("status_label")
        self.header_layout.addWidget(self.status_label)
        self.main_layout.addLayout(self.header_layout)
        self.content_label = QtWidgets.QLabel(parent=TaskCard)
        self.content_label.setWordWrap(True)
        self.content_label.setObjectName("content_label")
        self.main_layout.addWidget(self.content_label)
        self.time_label = QtWidgets.QLabel(parent=TaskCard)
        self.time_label.setObjectName("time_label")
        self.main_layout.addWidget(self.time_label)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setObjectName("button_layout")
        self.done_button = QtWidgets.QPushButton(parent=TaskCard)
        self.done_button.setObjectName("done_button")
        self.button_layout.addWidget(self.done_button)
        self.decline_button = QtWidgets.QPushButton(parent=TaskCard)
        self.decline_button.setObjectName("decline_button")
        self.button_layout.addWidget(self.decline_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.button_layout.addItem(spacerItem1)
        self.main_layout.addLayout(self.button_layout)

        self.retranslateUi(TaskCard)
        QtCore.QMetaObject.connectSlotsByName(TaskCard)

    def retranslateUi(self, TaskCard):
        _translate = QtCore.QCoreApplication.translate
        TaskCard.setWindowTitle(_translate("TaskCard", "Kartu Tugas"))
        TaskCard.setStyleSheet(_translate("TaskCard", "QFrame#taskCard {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dee2e6;\n"
"    border-radius: 15px;\n"
"    padding: 15px;\n"
"    margin: 8px 0;\n"
"}"))
        self.title_label.setText(_translate("TaskCard", "Daftar To-Do"))
        self.title_label.setStyleSheet(_translate("TaskCard", "QLabel#taskTitle {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #2c3e50;\n"
"    margin-bottom: 5px;\n"
"}"))
        self.status_label.setText(_translate("TaskCard", "Belum Selesai"))
        self.status_label.setStyleSheet(_translate("TaskCard", "QLabel#statusFinished {\n"
"    background-color: #d4edda;\n"
"    color: #155724;\n"
"    padding: 4px 8px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QLabel#statusNotYet {\n"
"    background-color: #f8d7da;\n"
"    color: #721c24;\n"
"    padding: 4px 8px;\n"
"    border-radius: 6px;\n"
"    font-size: 12px;\n"
"    font-weight: 500;\n"
"}"))
        self.content_label.setText(_translate("TaskCard", "Konten tugas akan ditampilkan di sini"))
        self.content_label.setStyleSheet(_translate("TaskCard", "QLabel#taskContent {\n"
"    font-size: 13px;\n"
"    color: #495057;\n"
"    background-color: #f8f9fa;\n"
"    padding: 8px;\n"
"    border: 1px solid #dee2e6;\n"
"    border-radius: 8px;\n"
"    margin: 4px 0;\n"
"}"))
        self.time_label.setText(_translate("TaskCard", "09:00 - 10:00"))
        self.time_label.setStyleSheet(_translate("TaskCard", "QLabel#taskTime {\n"
"    font-size: 12px;\n"
"    color: #6c757d;\n"
"    background-color: #f8f9fa;\n"
"    padding: 6px;\n"
"    border: 1px solid #dee2e6;\n"
"    border-radius: 8px;\n"
"}"))
        self.done_button.setText(_translate("TaskCard", "Selesai"))
        self.done_button.setStyleSheet(_translate("TaskCard", "QPushButton#doneButton {\n"
"    background-color: #28a745;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    border-radius: 8px;\n"
"    font-weight: 500;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QPushButton#doneButton:hover {\n"
"    background-color: #218838;\n"
"}"))
        self.decline_button.setText(_translate("TaskCard", "Tolak"))
        self.decline_button.setStyleSheet(_translate("TaskCard", "QPushButton#declineButton {\n"
"    background-color: #dc3545;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    border-radius: 8px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QPushButton#declineButton:hover {\n"
"    background-color: #c82333;\n"
"}"))
